# Generated by Django 3.0.5 on 2021-08-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='pasword1',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pasword2',
        ),
    ]
