# Generated by Django 3.0.5 on 2021-08-08 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(choices=[('TC1', 'TC1'), ('TC2', 'TC2'), ('DIC1', 'DIC1'), ('DIC2', 'DIC2'), ('DIC3', 'DIC3')], max_length=200)),
                ('description_classe', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_departement', models.CharField(choices=[('Génie électromécanique', 'Génie électromécanique'), ('Génie civil', 'Génie civil'), ('Génie informatique et telecoms', 'Génie informatique et telecoms'), ('Tronc Commun', 'Tronc Commun')], max_length=300)),
                ('mail_departement', models.EmailField(max_length=255, null=True)),
                ('numero_departement', models.CharField(max_length=300)),
                ('description_dept', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=300)),
                ('nom', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=300)),
                ('code_matiere', models.IntegerField()),
                ('coef_matiere', models.IntegerField()),
                ('credit_matiere', models.CharField(max_length=300)),
                ('quota_horaire', models.IntegerField()),
                ('description_matiere', models.CharField(max_length=300)),
                ('departemet', models.ManyToManyField(to='departement.Departement')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='departement.user')),
                ('contact_prof', models.CharField(max_length=300)),
                ('date_d_adhesion', models.DateField()),
                ('departemet', models.ManyToManyField(to='departement.Departement')),
            ],
            bases=('departement.user',),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='departement.user')),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=300)),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='departement.ClasseD')),
                ('departement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='departement.Departement')),
            ],
            bases=('departement.user',),
        ),
        migrations.CreateModel(
            name='Chef_departement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('diriger', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='departement.Departement')),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='departement.Professeur')),
            ],
        ),
    ]
