# Generated by Django 3.0.5 on 2021-08-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef_departement',
            name='image',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
