# Generated by Django 3.0.5 on 2021-08-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0002_auto_20210808_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='departement',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='departement',
            field=models.ManyToManyField(to='departement.Departement'),
        ),
    ]
